---
deployment:
  tasks:
    - export DEPLOYPATH=/home/majul764/public_html/
    # Copy Directories
    - /bin/cp -R api $DEPLOYPATH
    - /bin/cp -R brands $DEPLOYPATH
    - /bin/cp -R brochures $DEPLOYPATH
    - /bin/cp -R COPYRIGHT $DEPLOYPATH
    - /bin/cp -R events $DEPLOYPATH
    - /bin/cp -R favicon_io $DEPLOYPATH
    - /bin/cp -R lang $DEPLOYPATH
    - /bin/cp -R logo $DEPLOYPATH
    - /bin/cp -R products $DEPLOYPATH
    # Copy Core Files
    - /bin/cp *.html $DEPLOYPATH
    - /bin/cp *.php $DEPLOYPATH
    - /bin/cp *.css $DEPLOYPATH
    - /bin/cp *.js $DEPLOYPATH
    - /bin/cp *.webp $DEPLOYPATH
    - /bin/cp *.png $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH